######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 27 18:10:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS +=	main.h \
			window.h \
			renderer.h \
			md2.h \
			vector3d.h \

SOURCES +=	main.cpp \
			window.cpp \
			renderer.cpp \
			md2.cpp \
			vector3d.cpp \